apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  namespace: dask
  labels:
    component: scheduler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  namespace: dask
  labels:
    component: scheduler
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  namespace: dask
  labels:
    component: scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "dask.fullname" . }}-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ template "dask.fullname" . }}-scheduler
